2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152050-8lni321q/logs/debug.log
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152050-8lni321q/logs/debug-internal.log
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:init():666] found existing run on stack: 5ocgd7ry
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_run.py:_finish():2140] finishing run guyshani-tel-aviv-university/adversarial_gene_expr/5ocgd7ry
2025-01-12 15:20:50,581 ERROR   MainThread:19458 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-01-12 15:20:50,581 INFO    MainThread:19458 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_init.py:_jupyter_teardown():451] cleaning up jupyter logic
2025-01-12 15:20:50,581 INFO    MainThread:19458 [wandb_run.py:_atexit_cleanup():2380] got exitcode: 0
2025-01-12 15:20:50,582 INFO    MainThread:19458 [wandb_run.py:_restore():2362] restore
2025-01-12 15:20:50,582 INFO    MainThread:19458 [wandb_run.py:_restore():2368] restore done
2025-01-12 15:21:08,377 WARNING MainThread:19458 [wandb_init.py:init():1293] interrupted
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 667, in init
    latest_run.finish()
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 442, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 384, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2134, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2164, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2392, in _atexit_cleanup
    self._on_finish()
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2644, in _on_finish
    _ = exit_handle.wait(
        ^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-12 15:23:22,253 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152322-xs6449nv/logs/debug.log
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152322-xs6449nv/logs/debug-internal.log
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:_jupyter_setup():469] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x3d1336a90>
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:23:22,254 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:23:22,255 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:23:22,255 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:23:22,255 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:23:22,256 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:23:22,296 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:24:11,309 WARNING MainThread:19458 [wandb_init.py:init():1293] interrupted
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152435-xmppefy6/logs/debug.log
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152435-xmppefy6/logs/debug-internal.log
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:24:35,456 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:24:35,457 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:24:35,457 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:24:35,458 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:24:35,459 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:24:35,494 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:26:05,833 ERROR   MainThread:19458 [wandb_init.py:init():845] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:26:05,835 ERROR   MainThread:19458 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:27:44,615 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152744-oiuy8enq/logs/debug.log
2025-01-12 15:27:44,617 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_152744-oiuy8enq/logs/debug-internal.log
2025-01-12 15:27:44,617 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:27:44,617 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:27:44,617 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:27:44,617 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:27:44,617 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:27:44,618 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:27:44,618 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:27:44,619 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:27:44,656 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:29:15,030 ERROR   MainThread:19458 [wandb_init.py:init():845] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:29:15,035 ERROR   MainThread:19458 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:32:48,255 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_153248-l9d94oyj/logs/debug.log
2025-01-12 15:32:48,256 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_153248-l9d94oyj/logs/debug-internal.log
2025-01-12 15:32:48,256 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:32:48,256 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:32:48,256 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:32:48,256 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:32:48,256 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:32:48,257 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:32:48,257 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:32:48,258 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:32:48,296 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:34:18,698 ERROR   MainThread:19458 [wandb_init.py:init():845] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:34:18,702 ERROR   MainThread:19458 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:36:16,808 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/offline-run-20250112_153616-6317ssqw/logs/debug.log
2025-01-12 15:36:16,810 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/offline-run-20250112_153616-6317ssqw/logs/debug-internal.log
2025-01-12 15:36:16,810 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:36:16,810 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:36:16,810 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:36:16,810 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:36:16,812 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:36:16,812 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:36:16,816 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:36:16,817 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:36:16,835 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:37:47,336 ERROR   MainThread:19458 [wandb_init.py:init():845] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:37:47,340 ERROR   MainThread:19458 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 851, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-12 15:40:30,204 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_154030-ycok0g1b/logs/debug.log
2025-01-12 15:40:30,206 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_154030-ycok0g1b/logs/debug-internal.log
2025-01-12 15:40:30,206 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:40:30,206 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:40:30,206 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:40:30,206 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:40:30,207 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:40:30,207 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:40:30,207 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:40:30,208 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:40:30,225 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:40:52,574 WARNING MainThread:19458 [wandb_init.py:init():1293] interrupted
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-01-12 15:42:12,830 INFO    MainThread:19458 [wandb_init.py:_log_setup():523] Logging user logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_154212-6p3u97rl/logs/debug.log
2025-01-12 15:42:12,833 INFO    MainThread:19458 [wandb_init.py:_log_setup():524] Logging internal logs to /Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/wandb/run-20250112_154212-6p3u97rl/logs/debug-internal.log
2025-01-12 15:42:12,833 INFO    MainThread:19458 [wandb_init.py:init():641] calling init triggers
2025-01-12 15:42:12,833 INFO    MainThread:19458 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {'epochs': 200, 'latent_dim': 64, 'batch_size': 32, 'nb_layers': 2, 'hdim': 256, 'lr': 0.0005, 'nb_critic': 5}
2025-01-12 15:42:12,833 INFO    MainThread:19458 [wandb_init.py:init():674] starting backend
2025-01-12 15:42:12,833 INFO    MainThread:19458 [wandb_init.py:init():678] sending inform_init request
2025-01-12 15:42:12,833 INFO    MainThread:19458 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-12 15:42:12,834 INFO    MainThread:19458 [wandb_init.py:init():693] backend started and connected
2025-01-12 15:42:12,834 INFO    MainThread:19458 [wandb_run.py:_label_probe_notebook():1226] probe notebook
2025-01-12 15:42:12,835 INFO    MainThread:19458 [wandb_init.py:init():786] updated telemetry
2025-01-12 15:42:12,860 INFO    MainThread:19458 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-01-12 15:42:19,692 WARNING MainThread:19458 [wandb_init.py:init():1293] interrupted
Traceback (most recent call last):
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/Documents/PHD/Aim_2/cycle_GAN/.venv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyshani/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
